### ISSUE TITLE
No sawtooth_ubuntu_installation.sh

### ISSUE THREAD

**Issue by renkarnation** [Primechain/blockchain-ekyc-sawtooth#2]
can you re upload the sawtooth_ubuntu_installation.sh i can't find the sawtooth_ubuntu_installation.sh on the sawtooth/shell-scripts. Thankyou

**Comment by rahul0812** [comment]
It is 'sawtooth_ubuntu_setup.sh' instead of 'sawtooth_ubuntu_installation.sh'. Updated the setup guide accordingly.

**Comment by renkarnation** [comment]
Thank you, I'm just a little bit confused.

**Comment by rahul0812** [comment]
Let me know if you face any issues.
